[package]
name = 'ridit'
version = '0.1.0'
edition = '2018'

[dependencies]
structopt = '0.3'
directories = '3.0'
toml = '0.5'
tokio-retry = '0.3'
imagesize = '0.9.0'

[dependencies.anyhow]
version = '1'
features = [
    'std',
    'backtrace',
]

[dependencies.reqwest]
version = '0.11'
features = ['json']

[dependencies.tokio]
version = '1.10'
features = ['full']

[dependencies.serde]
version = '1.0'
features = ['derive']
