[package]
name = 'ridit'
version = '0.1.0'
edition = '2018'

[dependencies]
structopt = '0.3'
directories = '3.0'
anyhow = '1'
toml = '0.5'
reqwest = {version = '0.11', features = ['json']}

[dependencies.backoff]
version = '0.3'
features = ['tokio']

[dependencies.tokio]
version = '1.10'
features = ['full']

[dependencies.serde]
version = '1.0'
features = ['derive']
